### PR TITLE
Test builds for fixing MacOS 15 support

### PR DESCRIPTION
**Pull request by ryanvolz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by michaelld** [comment]
@ryanvolz how do I direct conda / mamba (etc) to install this UHD build?

**Comment by ryanvolz** [comment]
> @ryanvolz how do I direct conda / mamba (etc) to install this UHD build?

I'm skeptical that this actually changed anything, but the procedure would be:

1) Go to the [Azure artifacts list](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1099942&view=artifacts&pathAsName=false&type=publishedArtifacts) from this CI run, find the one for the platform and Python version that you want, hover over it and go all the way to the right to click the three dots, then click to download the artifact.

2) That is a nested archive, and after unpacking it all you will find an `osx-arm64` folder and inside of it a `uhd-4.7.0.0-pyWHATEVER_4.conda` package. You can then `conda install PATH/TO/THAT/PACKAGE/FILE.conda` from within the environment where you already have UHD installed, and it will update to that build.

**Comment by ryanvolz** [comment]
Running `otool -L` on the `libpyuhd` from this build would be helpful to see if the CMake changes had any effect.

**Comment by michaelld** [comment]
@ryanvolz 
```uhd@m-mbrp16-enet osx-arm64 % conda install uhd-4.7.0.0-py312hcf98d66_4.conda

Downloading and Extracting Packages:


## Package Plan ##

  environment location: /Users/uhd/miniforge3

  added / updated specs:
    - conda_artifacts_20241204.1.1_osx_arm64_numpy2.0python3.12.____cpython/osx-arm64::uhd==4.7.0.0=py312hcf98d66_4


The following packages will be UPDATED:

  uhd                conda-forge::uhd-4.6.0.0-py312h1afdc0~ --> conda_artifacts_20241204.1.1_osx_arm64_numpy2.0python3.12.____cpython::uhd-4.7.0.0-py312hcf98d66_4



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
uhd@m-mbrp16-enet osx-arm64 %
uhd@m-mbrp16-enet osx-arm64 %
uhd@m-mbrp16-enet osx-arm64 %
uhd@m-mbrp16-enet osx-arm64 % uhd_find_devices
dyld[34768]: missing symbol called
zsh: abort      uhd_find_devices
uhd@m-mbrp16-enet osx-arm64 % which uhd_find_devices
/Users/uhd/miniforge3/bin/uhd_find_devices
uhd@m-mbrp16-enet osx-arm64 % python3.12
Python 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 15:57:01) [Clang 17.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import uhd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/uhd/miniforge3/lib/python3.12/site-packages/uhd/__init__.py", line 10, in <module>
    from . import types
  File "/Users/uhd/miniforge3/lib/python3.12/site-packages/uhd/types.py", line 10, in <module>
    from . import libpyuhd as lib
ImportError: dlopen(/Users/uhd/miniforge3/lib/python3.12/site-packages/uhd/libpyuhd.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '__ZN5boost10filesystem6detail28directory_iterator_constructERNS0_18directory_iteratorERKNS0_4pathENS0_17directory_optionsEPNS1_25directory_iterator_paramsEPNS_6system10error_codeE'
```

**Comment by michaelld** [comment]
```uhd@m-mbrp16-enet uhd % otool -L libpyuhd.cpython-312-darwin.so
libpyuhd.cpython-312-darwin.so:
	/Users/runner/miniforge3/conda-bld/uhd_1733349912104/work/host/python/lib/python3.12/site-packages/uhd/libpyuhd.cpython-312-darwin.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libuhd.4.7.0.dylib (compatibility version 4.7.0, current version 4.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)```

**Comment by ryanvolz** [comment]
Hrm, I forgot that installing the package file directly doesn't check dependencies, so that's probably the first problem.

I think you can treat the parent directory of what you've unzipped as a conda channel, and then it can work. Something like `conda install -c /FULL/PATH/TO/WHERE/YOU/UNZIPPED uhd` where the path you provide is the directory that contains `osx-arm64/`.



> ```
> libpyuhd.cpython-312-darwin.so:
> 	/Users/runner/miniforge3/conda-bld/uhd_1733349912104/work/host/python/lib/python3.12/site-packages/uhd/libpyuhd.cpython-312-darwin.so (compatibility version 0.0.0, current version 0.0.0)
> 	@rpath/libuhd.4.7.0.dylib (compatibility version 4.7.0, current version 4.7.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
> 	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)```
> ```

So I think that's the same as before, and I've failed to get the build directory out of the self ID.

**Comment by michaelld** [comment]
```
uhd@m-mbrp16-enet conda_artifacts_20241204.1.1_osx_arm64_numpy2.0python3.12.____cpython % conda install -c . uhd
Channels:
 - .
 - conda-forge
 - defaults
 - file:///Users/uhd/miniforge3/TMP/conda_artifacts_20241204.1.1_osx_arm64_numpy2.0python3.12.____cpython
Platform: osx-arm64
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel . <https://conda.anaconda.org/.>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.


uhd@m-mbrp16-enet conda_artifacts_20241204.1.1_osx_arm64_numpy2.0python3.12.____cpython % pwd
/Users/uhd/miniforge3/TMP/conda_artifacts_20241204.1.1_osx_arm64_numpy2.0python3.12.____cpython
uhd@m-mbrp16-enet conda_artifacts_20241204.1.1_osx_arm64_numpy2.0python3.12.____cpython % ll
total 10144
-rw-r--r--@ 1 uhd  staff      976 Dec  4 17:40 channeldata.json
-rw-r--r--@ 1 uhd  staff     2365 Dec  4 17:40 index.html
drwxr-xr-x@ 7 uhd  staff      224 Dec  4 17:40 noarch/
drwxr-xr-x@ 7 uhd  staff      224 Dec  4 17:40 osx-64/
drwxr-xr-x@ 8 uhd  staff      256 Dec  5 13:37 osx-arm64/
-rw-r--r--@ 1 uhd  staff  5183795 Dec  5  2024 uhd-feedstock_conda_artifacts_20241204.1.1_osx_arm64_numpy2.0python3.12.____cpython.zip
drwxr-xr-x@ 3 uhd  staff       96 Dec  4 17:40 uhd_1733352035560/
drwxr-xr-x@ 3 uhd  staff       96 Dec  4 17:40 uhd_1733352036480/
```

**Comment by ryanvolz** [comment]
Try `conda install -c ../build_artifacts uhd` from within `build_artifacts`. I think it's confusing the `.` path as a channel name instead of a path. A full path from the root dir would also work, or maybe something with `file://` prefixed.

**Comment by ryanvolz** [comment]
Anything else I can add to a build that would help with debugging? Like enabling debug symbols? Anything to assist with valgrind or whatever macOS alternative?

**Comment by michaelld** [comment]
Turns out it needs the full path, not a partial path .,.. go figure! `uhd_find_devices` now works; instantiation the Python USRP object still fails as noted

**Comment by michaelld** [comment]
Here's the backtrace of the error:
```
uhd@m-mbrp16-enet miniforge3 % lldb python3.12
(lldb) target create "python3.12"
Current executable set to '/Users/uhd/miniforge3/bin/python3.12' (arm64).
(lldb) b malloc_error_break
Breakpoint 1: where = libsystem_malloc.dylib`malloc_error_break, address = 0x00000001802860f4
(lldb) run
Process 35825 launched: '/Users/uhd/miniforge3/bin/python3.12' (arm64)
Python 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 15:57:01) [Clang 17.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import uhd
>>> usrp=uhd.usrp.MultiUSRP()
[INFO] [UHD] Mac OS; Clang version 18.1.8 ; Boost_108600; UHD_4.7.0.0-release
[INFO] [MPMD FIND] Found MPM devices, but none are reachable for a UHD session. Specify find_all to find all devices.
python3.12(35825,0x1eb6b7840) malloc: *** error for object 0x1e9595cc0: pointer being freed was not allocated
python3.12(35825,0x1eb6b7840) malloc: *** set a breakpoint in malloc_error_break to debug
Process 35825 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x00000001863da0f4 libsystem_malloc.dylib`malloc_error_break
libsystem_malloc.dylib`malloc_error_break:
->  0x1863da0f4 <+0>:  pacibsp
    0x1863da0f8 <+4>:  stp    x29, x30, [sp, #-0x10]!
    0x1863da0fc <+8>:  mov    x29, sp
    0x1863da100 <+12>: nop
Target 0: (python3.12) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x00000001863da0f4 libsystem_malloc.dylib`malloc_error_break
    frame #1: 0x00000001863b9490 libsystem_malloc.dylib`malloc_vreport + 748
    frame #2: 0x00000001863bd0a8 libsystem_malloc.dylib`malloc_report + 64
    frame #3: 0x00000001863db1a4 libsystem_malloc.dylib`find_zone_and_free + 528
    frame #4: 0x0000000100c2020c libc++.1.0.dylib`std::__1::locale::~locale() + 72
    frame #5: 0x0000000100b6d348 libboost_serialization.dylib`boost::archive::basic_text_oprimitive<std::__1::basic_ostream<char, std::__1::char_traits<char>>>::basic_text_oprimitive(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool) + 348
    frame #6: 0x0000000100b7389c libboost_serialization.dylib`boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::text_oarchive_impl(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, unsigned int) + 40
    frame #7: 0x0000000102c12f50 libuhd.4.7.0.dylib`uhd::usrprio_rpc::boost_serialization_archive_utils::get_version() + 176
    frame #8: 0x0000000102c120b4 libuhd.4.7.0.dylib`uhd::usrprio_rpc::rpc_client::rpc_client(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned int, unsigned int) + 340
    frame #9: 0x0000000102c17cb8 libuhd.4.7.0.dylib`uhd::usrprio_rpc::usrprio_rpc_client::usrprio_rpc_client(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) + 64
    frame #10: 0x0000000102c1b368 libuhd.4.7.0.dylib`uhd::niusrprio::niusrprio_session::enumerate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::vector<uhd::usrprio_rpc::usrprio_device_info, std::__1::allocator<uhd::usrprio_rpc::usrprio_device_info>>&) + 128
    frame #11: 0x0000000102b0d638 libuhd.4.7.0.dylib`uhd::usrp::x300::pcie_manager::find(uhd::device_addr_t const&, bool) + 316
    frame #12: 0x0000000102acefac libuhd.4.7.0.dylib`x300_find(uhd::device_addr_t const&) + 3040
    frame #13: 0x0000000102c8d134 libuhd.4.7.0.dylib`uhd::device::make(uhd::device_addr_t const&, uhd::device::device_filter_t, unsigned long) + 224
    frame #14: 0x0000000102463d90 libuhd.4.7.0.dylib`uhd::usrp::multi_usrp::make(uhd::device_addr_t const&) + 324
    frame #15: 0x0000000100f90334 libpyuhd.cpython-312-darwin.so`void pybind11::detail::initimpl::factory<std::__1::shared_ptr<uhd::usrp::multi_usrp> (*)(uhd::device_addr_t const&), pybind11::detail::void_type (*)(), std::__1::shared_ptr<uhd::usrp::multi_usrp> (uhd::device_addr_t const&), pybind11::detail::void_type ()>::execute<pybind11::class_<uhd::usrp::multi_usrp, std::__1::shared_ptr<uhd::usrp::multi_usrp>>>(pybind11::class_<uhd::usrp::multi_usrp, std::__1::shared_ptr<uhd::usrp::multi_usrp>>&) &&::'lambda'(pybind11::detail::value_and_holder&, uhd::device_addr_t const&)::operator()(pybind11::detail::value_and_holder&, uhd::device_addr_t const&) const + 52
    frame #16: 0x0000000100f9026c libpyuhd.cpython-312-darwin.so`void pybind11::cpp_function::initialize<void pybind11::detail::initimpl::factory<std::__1::shared_ptr<uhd::usrp::multi_usrp> (*)(uhd::device_addr_t const&), pybind11::detail::void_type (*)(), std::__1::shared_ptr<uhd::usrp::multi_usrp> (uhd::device_addr_t const&), pybind11::detail::void_type ()>::execute<pybind11::class_<uhd::usrp::multi_usrp, std::__1::shared_ptr<uhd::usrp::multi_usrp>>>(pybind11::class_<uhd::usrp::multi_usrp, std::__1::shared_ptr<uhd::usrp::multi_usrp>>&) &&::'lambda'(pybind11::detail::value_and_holder&, uhd::device_addr_t const&), void, pybind11::detail::value_and_holder&, uhd::device_addr_t const&, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::detail::is_new_style_constructor>(pybind11::class_<uhd::usrp::multi_usrp, std::__1::shared_ptr<uhd::usrp::multi_usrp>>&&, void (*)(pybind11::detail::value_and_holder&, uhd::device_addr_t const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::detail::is_new_style_constructor const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 164
    frame #17: 0x0000000100f901a0 libpyuhd.cpython-312-darwin.so`void pybind11::cpp_function::initialize<void pybind11::detail::initimpl::factory<std::__1::shared_ptr<uhd::usrp::multi_usrp> (*)(uhd::device_addr_t const&), pybind11::detail::void_type (*)(), std::__1::shared_ptr<uhd::usrp::multi_usrp> (uhd::device_addr_t const&), pybind11::detail::void_type ()>::execute<pybind11::class_<uhd::usrp::multi_usrp, std::__1::shared_ptr<uhd::usrp::multi_usrp>>>(pybind11::class_<uhd::usrp::multi_usrp, std::__1::shared_ptr<uhd::usrp::multi_usrp>>&) &&::'lambda'(pybind11::detail::value_and_holder&, uhd::device_addr_t const&), void, pybind11::detail::value_and_holder&, uhd::device_addr_t const&, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::detail::is_new_style_constructor>(pybind11::class_<uhd::usrp::multi_usrp, std::__1::shared_ptr<uhd::usrp::multi_usrp>>&&, void (*)(pybind11::detail::value_and_holder&, uhd::device_addr_t const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::detail::is_new_style_constructor const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 40
    frame #18: 0x0000000100e8cc08 libpyuhd.cpython-312-darwin.so`pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 4876
    frame #19: 0x00000001000c65dc python3.12`cfunction_call + 136
    frame #20: 0x000000010006a6d8 python3.12`_PyObject_MakeTpCall + 316
    frame #21: 0x00000001001997c0 python3.12`_PyEval_EvalFrameDefault + 57428
    frame #22: 0x000000010006ab60 python3.12`_PyObject_FastCallDictTstate + 324
    frame #23: 0x00000001000edc5c python3.12`slot_tp_init + 320
    frame #24: 0x00000001000e5cb0 python3.12`type_call + 496
    frame #25: 0x0000000100e8818c libpyuhd.cpython-312-darwin.so`pybind11_meta_call + 56
    frame #26: 0x000000010006a6d8 python3.12`_PyObject_MakeTpCall + 316
    frame #27: 0x00000001001997c0 python3.12`_PyEval_EvalFrameDefault + 57428
    frame #28: 0x000000010018a83c python3.12`PyEval_EvalCode + 300
    frame #29: 0x00000001002041a8 python3.12`run_mod + 228
    frame #30: 0x00000001002046c0 python3.12`PyRun_InteractiveOneObjectEx + 732
    frame #31: 0x0000000100203530 python3.12`_PyRun_InteractiveLoopObject + 176
    frame #32: 0x0000000100202e74 python3.12`_PyRun_AnyFileObject + 112
    frame #33: 0x0000000100207818 python3.12`PyRun_AnyFileExFlags + 208
    frame #34: 0x000000010022feb0 python3.12`Py_RunMain + 3552
    frame #35: 0x0000000100230984 python3.12`pymain_main + 628
    frame #36: 0x00000001000037c0 python3.12`main + 56
    frame #37: 0x0000000186220274 dyld`start + 2840
```

**Comment by michaelld** [comment]
so ... it might be a Boost issue

**Comment by ryanvolz** [comment]
> so ... it might be a Boost issue

Intriguing. What Boost version do you have in a non-conda-forge build that works? I could try building with that.

**Comment by michaelld** [comment]
@ryanvolz hmmm ... doesn't look good for those builds :(

**Comment by michaelld** [comment]
I will look into getting Boost 1.82 into MacPorts, even just a local install, to see if I get issues with it

**Pull request merged**
